# Generated by Django 4.1.1 on 2022-11-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kbz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_time', models.CharField(max_length=255)),
                ('merch_code', models.CharField(max_length=255)),
                ('merch_order_id', models.CharField(max_length=255)),
                ('mm_order_id', models.CharField(max_length=255)),
                ('trans_currency', models.CharField(max_length=255)),
                ('total_amount', models.CharField(max_length=255)),
                ('trade_status', models.CharField(max_length=255)),
                ('trans_end_time', models.CharField(max_length=255)),
                ('callback_info', models.CharField(max_length=255)),
                ('nonce_str', models.CharField(max_length=255)),
                ('sign_type', models.CharField(max_length=255)),
                ('appid', models.CharField(max_length=40)),
                ('sign', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='kbz_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.kbz')),
            ],
        ),
    ]
